### ISSUE TITLE
logo-swissstoreconfig-ch.png is missing

### ISSUE THREAD

**Issue by nickweisser** [integer-net/Magento-CH#1]
The installer is referencing the PNG with skin/install/base/default/images/logo-swissstoreconfig-ch.png, but it is located in skin/adminhtml/default/default/germanstoreconfig/logo-swissstoreconfig-ch.png

**Comment by cphilipp** [comment]
Ok, fixed the problem. Commit: 432d6eebb27e274e759fb19ed62a179400b7e7d5
